export const CITY_DESCRIPTIONS: Record<string, string> = {
  naha: "Naha, Okinawa's vibrant capital city, offers a mix of modern living and traditional culture. Home to the famous Kokusai Street and Shuri Castle, residents enjoy easy access to shopping, dining, and entertainment while experiencing authentic Okinawan lifestyle.",
  chatan: "Chatan is a lively coastal town known for its beautiful beaches and American Village. Popular among both locals and military families, it offers oceanfront living with modern amenities, diverse dining options, and excellent shopping at the Mihama American Village.",
  ginowan: "Ginowan combines urban convenience with peaceful residential areas. Home to several universities and the Okinawa Convention Center, it offers a perfect balance of educational opportunities, cultural activities, and quiet neighborhood living.",
  urasoe: "Urasoe, rich in history with its famous castle ruins, provides a peaceful suburban lifestyle while maintaining easy access to Naha's urban amenities. The city offers beautiful parks, historical sites, and modern shopping facilities.",
  okinawa: "Okinawa City, also known as Koza, is a dynamic multicultural hub. The city features a unique blend of American and Okinawan culture, with live music venues, traditional markets, and modern shopping centers like Aeon Mall Okinawa.",
  uruma: "Uruma City, formed from the merger of four former cities, offers diverse living environments from coastal areas to hillside communities. The city is known for its beautiful beaches, historic castle ruins, and convenient location central to many military bases.",
  yomitan: "Yomitan Village, known for its pottery and traditional crafts, offers a more relaxed, rural lifestyle. The area features beautiful beaches, cultural facilities, and a strong sense of community while maintaining easy access to urban amenities.",
  kitanakagusuku: "Kitanakagusuku offers peaceful suburban living with stunning ocean views. The village is known for its historical sites including Nakagusuku Castle ruins, while providing convenient access to shopping centers and nearby cities.",
  nakagusuku: "Nakagusuku Village, home to the UNESCO World Heritage Nakagusuku Castle ruins, provides a perfect blend of historical significance and modern living. The area offers peaceful residential neighborhoods with easy access to major cities.",
  nishihara: "Nishihara, home to the University of the Ryukyus, has a youthful, educational atmosphere. The town offers a mix of student housing and family residences, with convenient access to shopping and dining.",
  onna: "Onna Village is a stunning coastal area known for its pristine beaches and luxury resorts. Popular for its diving spots and scenic Cape Maeda, it offers a perfect blend of natural beauty and modern amenities, with many residential areas providing spectacular ocean views.",
  kadena: "Kadena Town, adjacent to Kadena Air Base, is a vibrant community that perfectly balances military convenience with local charm. The area offers excellent housing options for both military and civilian residents, with easy access to shopping, dining, and entertainment."
};

export const BASE_DESCRIPTIONS: Record<string, string> = {
  'kadena air base': "Kadena Air Base is the largest U.S. military installation in the Asia-Pacific region. The surrounding area offers a variety of housing options, from modern apartments to traditional homes, with excellent access to both American and Japanese amenities.",
  'camp foster': "Camp Foster, located in central Okinawa, is surrounded by vibrant neighborhoods offering diverse housing options. The area provides easy access to shopping centers, restaurants, and beaches while maintaining a strong military community feel.",
  'camp kinser': "Camp Kinser's location offers residents proximity to both Naha City and the Urasoe area. The surrounding neighborhoods provide a mix of modern apartments and traditional homes, with convenient access to shopping and dining options.",
  'camp hansen': "Camp Hansen, situated in northern Okinawa, offers a more relaxed, countryside atmosphere. The area features affordable housing options with easy access to beautiful beaches and natural attractions.",
  'camp schwab': "Camp Schwab's northern location provides a peaceful living environment away from urban centers. The area offers affordable housing options and access to some of Okinawa's most pristine beaches and diving spots.",
  'white beach': "White Beach Naval Facility area offers a unique coastal living experience. Residents enjoy proximity to beautiful beaches, local markets, and a mix of housing options from modern apartments to traditional Okinawan homes.",
  'mcas futenma': "The area around MCAS Futenma provides convenient access to both military facilities and local amenities. Housing options range from modern apartments to traditional homes, with easy access to shopping centers and restaurants.",
  'torii station': "Torii Station's location offers a perfect blend of convenience and tranquility. The surrounding area provides various housing options with easy access to both military facilities and local attractions."
};
